#creates Replicaset
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 164910480407.dkr.ecr.us-east-1.amazonaws.com/frontend:0.0.6
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # port no that your service has to listern and this is the port you will access
      targetPort: 80  # Target port forwards the request to the backebd pod
  type: LoadBalancer


---
